# Generated by Django 5.0.7 on 2024-12-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('fees_per_credit_hour', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
